wallpaper {
  monitor = HDMI-A-1
            path = /home/neotop/Pictures/wallpapers/eva66.jpg
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
            path = /home/neotop/Pictures/wallpapers/eva66.jpg
  fit_mode = cover
}
